config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "items#index"
  resources :items, only: [:new, :create, :show, :edit, :update] do
    collection do
      get "search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'レディース' },
    { id: 2, name: 'メンズ' },
    { id: 3, name: 'ベビー・キッズ' },
    { id: 4, name: 'インテリア・住まい・小物' },
    { id: 5, name: '本・音楽・ゲーム' },
    { id: 6, name: 'おもちゃ・ホビー・グッズ' },
    { id: 7, name: '家電・スマホ・カメラ' },
    { id: 8, name: 'スポーツ・レジャー' },
    { id: 9, name: 'ハンドメイド' },
    { id: 10, name: 'その他' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :user
  has_one_attached :image
  belongs_to_active_hash :category
  
  with_options presence: true do
    validates :image
    validates :name
    validates :price
  end

  validates :category_id, numericality: { greater_than_or_equal_to:1 ,less_than_or_equal_to:10, message: "is invalid" }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "price", "category_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :items

  def self.ransackable_attributes(auth_object = nil)
    ["nickname"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:show, :edit, :update]
  before_action :redirect_to_show, only: [:edit, :update]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def search
     # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :category_id, :price).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def redirect_to_show
    return redirect_to root_path if current_user.id != @item.user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, id: 'new_item', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="name-field">
    <span>■ 名前</span>
    <%= f.text_field :name %>
  </div>
  <div class="image-field">
    <span>■ 画像</span>
    <div class="click-upload">
      <%= f.file_field :image %>
    </div>
  </div>
    <div class="category-field">
      <span>■ カテゴリー</span>
      <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "---"} %>
    </div>
    <div class="pricefield">
      <span>■ 価格</span>
      <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
    </div>
  <div class="submit-btn">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h3>編集ページ</h3>
<%= render partial: 'form' %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<h3>トップページ</h3>
<h3><%= link_to '商品出品', new_item_path%></h3>
<h3><%= link_to '商品検索', search_items_path%></h3>
<% @items.each do |item| %>
  <div class="posted-content">
    <%= image_tag item.image %><br>
    <%= item.name%><br>
    <%= link_to '詳細', item_path(item.id)%>
  </div>
<% end %>

app/views/items/new.html.erb
<h3>新規投稿ページ</h3>
<%= render partial: "form" %>

app/views/items/search.html.erb
<%= render "shared/header" %>
<h3>検索ページ</h3>
<h3><%= link_to 'トップページへ戻る', root_path%></h3>
<div class='item-contents' id="detailed-search-result-wrapper">
  <%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>
    <div class="search-field">
      <%= f.label :name, '商品名' %>
      <br>
      <%= f.text_field :name, placeholder: '商品名', value: params[:q]&.dig(:name) %>
    </div>
     <div class="search-field">
      <%= f.label :user_nickname_cont, '出品者名' %>
      <br>
      <%= f.text_field :user_nickname_cont, placeholder: '出品者名' %>
    </div>
     <div class="search-field">
      <%= f.label :category_id_in, 'カテゴリ' %>
      <br>
      <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name) %>
    </div>
    <div class="search-field">
      <%= f.label :price_gteq, '価格'%>
      <br>
      <%= f.number_field :price_gteq %> 円以上
      <br>
      <%= f.number_field :price_lteq %> 円以下
    </div>
    <%= f.submit '検索' %>
  <% end %>
  <ul class='item-lists' id="detailed-search-result">
    <% @items.each do |item| %>
      <li class='list'>
        <div class="posted-content">
          <%= image_tag item.image %><br>
          <%= item.name%><br>
          <%= link_to '詳細', item_path(item.id)%>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/items/show.html.erb
<h3>詳細ページ</h3>
<div class="posted-content">
  <%= image_tag @item.image %><br>
  <table>
    <tr>
      <td>商品名</td>
      <td><%= @item.name%></td>
    </tr>
    <tr>
      <td>カテゴリー</td>
      <td><%= @item.category.name%></td>
    </tr>
    <tr>
      <td>価格</td>
      <td><%= @item.price%></td>
    </tr>
    <tr>
      <td>出品者</td>
      <td><%= @item.user.nickname%></td>
    </tr>
  </table>
  <% if user_signed_in? && current_user.id == @item.user_id%>
    <%= link_to '編集', edit_item_path(@item.id)%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAppRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= search_form_for Item.ransack(params[:q]), url: search_items_path, html: {class: "search-form"} do |f| %>
      <%= f.text_field :name, placeholder: '商品名から探す', class: 'input-box' %>
      <br>
      <%= f.label :submit, class: "search-button" do %>
        <input type="submit" value="検索" class="send">
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
      <% end %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li class="user_name" >ユーザー名： <%= "#{current_user.nickname}" %></li>
      <li class="logout" ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li class="login"><%= link_to 'ログイン', new_user_session_path %></li>
      <li class="sign-up"><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</header>